### ISSUE TITLE
Reduce complexity

### ISSUE THREAD

**Issue by retog** [ssb-ngi-pointer/ssb-http-auth-spec#5]
At the core, this specification shall allow an HTTP client to prove to an HTTP Server that they own an SSB identity, without ̣- of course - having to disclose the private key.

For this, we don't need switching connections and protocols. 

https://github.com/snwfdhmp/efs#authentication-protocol shows a simple way how this can be achieved:

|Server|Client|
|---|---|
||Hello, I'm user A|
|Hello user A, use this Nonce for authentication||
||Here is the signed Nonce|
|Here is your JWT token||

In an SSB context the client might use `muxrpc` to get the `sbot` sign the nonce, but this should be outside the scope of this specification as it unnecessarily restricts the way clients can prove to own an SSB identity.

Such a simpler approach can be use for the use-cases the spec authors had in mind but is significantly more generic and could for example be used to access a remote SSB Client from a device with minimal resources from a network where only https connections can be established.

**Comment by staltz** [comment]
Hmm, feel free to make a separate and more generalized spec, but I think it's worth keeping this one in place because it also is a guide on how to implement auth as is currently the case in go-ssb-room, without having to actually read source code.

**Comment by retog** [comment]
This repo claims to be a spec and not code documentation. As a spec it should be as straight forward and easy as possible to implement.

Now, how can I client that possesses an SSB Private Key authenticate to an HTTP service?

If I understand correctly, to do this over HTTP with the spec described here, they would have to connect to the service via Websockets, perform a Secure Handshake, wait for an RPC message, send a login request via HTTP, get the challenge via RPC message, answer the challenge, eventually get an answer to the HTTP login request with a cookie that allows for authenticated requests via HTTP. To me, this doesn't only seem unnecessarily complex, I also don't understand why I need this authenticated HTTP requests, given that I already have an SHS authenticated connection to the server.

**Comment by staltz** [comment]
Sorry, you probably should have given all this feedback way back then when we were designing this spec and we were very open to feedback. What you're talking about is modifying this so much that it would be a different spec. Feel free to write that yourself.

**Comment by retog** [comment]
Ok. Wondering when and where the design discussions took place, so I don't miss the next one.

**Comment by staltz** [comment]
Usually on SSB. E.g. `%ZkEpEhdPJa0wFmURaBo2O1sUiLOe/I1VosK/1HNtukw=.sha256` I often ask feedback for these things. E.g. I have a new proposal called "broker auth" posted yesterday that I'm looking for feedback.
